<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/13
 * Time: 12:05
 */

namespace App\Extensions;


use Encore\Admin\Form\Field;

class MarkdownEditor extends Field
{
    protected $view='admin.markdown-editor';
    protected static $css = 'vendor/markdown/css/editormd.min.css';
    protected static $js = [
        'vendor/markdown/js/editormd.min.js',
    ];
    public function render()
    {
        $value = $this->value;
        $name = $this->formatName($this->column);
        $this->script = <<<EOF
       
    $(function() {
        editormd("doc", {
            width: "95%",
            height: 640,
            tex              : true,
            tocm             : true,
            emoji            : true,
            taskList         : true,
            searchReplace    : true,
            htmlDecode       : "style,script,iframe",
            flowChart        : true,
            sequenceDiagram  : true,
            path : "/vendor/markdown/lib/",
            toolbarIcons : function() {
                return ["undo", "redo", "|", "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|", "h1", "h2", "h3", "h4", "h5", "h6", "|", "list-ul", "list-ol", "hr", "|", "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime", "emoji", "html-entities", "pagebreak", "||", "goto-line", "watch", "clear", "preview", "fullscreen"]
            },
            imageUpload : true,
            imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL : "http://localhost.webapitestclient.com/markdown/upload",
            saveHTMLToTextarea : true,
            onchange:function(){
                var html = $("textarea[name={$this->id}-markdown-doc]").val();
                $("textarea[name={$this->id}]").val(html);
            }
        });
    });


EOF;

        return parent::render(); // TODO: Change the autogenerated stub
    }
}